# Generated by Django 5.2.6 on 2025-09-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ente_emisor', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField(max_length=16)),
                ('moneda', models.CharField(max_length=3)),
                ('pagos_realizados', models.IntegerField(max_length=2)),
                ('pagos_totales', models.IntegerField(max_length=2)),
                ('lugar_gastado', models.CharField(max_length=128)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_gasto', models.DateField()),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mediopago')),
            ],
        ),
    ]
