# Generated by Django 5.2.6 on 2025-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='pagos_realizados',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='pagos_totales',
            field=models.IntegerField(),
        ),
    ]
