# Generated by Django 5.2.6 on 2025-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='monto_pendiente',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gasto',
            name='titulo',
            field=models.CharField(default='', max_length=32),
        ),
    ]
