# Generated by Django 5.2.6 on 2025-09-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gasto_monto_alter_gasto_pagos_realizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('finanzas', 'Finanzas'), ('salud', 'Salud'), ('educacion', 'Educación'), ('transporte', 'Transporte'), ('alimentacion', 'Alimentación'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
