# Generated by safe migration script - Cleanup Project tables
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_remaining_grupo_models'),
    ]

    operations = [
        # Eliminar tablas Project de manera segura
        migrations.RunSQL(
            sql="""
            -- Eliminar tabla api_project_invitation (tiene FK a api_project)
            DROP TABLE IF EXISTS api_project_invitation CASCADE;
            
            -- Eliminar tabla api_project_membership (tiene FK a api_project)  
            DROP TABLE IF EXISTS api_project_membership CASCADE;
            
            -- Eliminar tabla api_project
            DROP TABLE IF EXISTS api_project CASCADE;
            """,
            reverse_sql="""
            -- NOTA: Esta migración no es completamente reversible
            -- porque no guardamos los datos de las tablas eliminadas.
            -- Si necesitas revertir, restaura desde backup.
            SELECT 1; -- No-op para que la migración sea válida
            """,
            state_operations=[
                # Le decimos a Django que estos modelos ya no existen
                # (aunque no los tengamos definidos en models.py)
            ]
        ),
        
        # Mensaje informativo
        migrations.RunSQL(
            sql="SELECT 'Tablas Project eliminadas exitosamente' as mensaje;",
            reverse_sql="SELECT 'Migración revertida (parcialmente)' as mensaje;"
        ),
    ]