# Generated by Django 5.2.6 on 2025-09-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gasto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='extra',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('finanzas', 'Finanzas'), ('salud', 'Salud'), ('transporte', 'Transporte'), ('comida', 'Comida'), ('indumentaria', 'Indumentaria'), ('tecnologia', 'Tecnología'), ('inversiones', 'Inversiones'), ('otros', 'Otros')], default='otros', max_length=24),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='comentarios',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar Americano'), ('RS', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('NA', 'Otros')], default='ARS', max_length=3),
        ),
    ]
