# Generated by Django 5.2.6 on 2025-09-08 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mediopago_extra_alter_gasto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='lugar_gastado',
            new_name='vendedor',
        ),
    ]
