# Generated by Django 5.2.6 on 2025-09-15 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gasto_user_mediopago_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(db_index=True, help_text='JWT Token ID (jti claim)', max_length=255, unique=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='Last activity timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is still active')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string for tracking different devices')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_token_activity',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['token_jti'], name='api_token_a_token_j_99acef_idx'), models.Index(fields=['user', 'is_active'], name='api_token_a_user_id_b2a8a4_idx'), models.Index(fields=['last_activity'], name='api_token_a_last_ac_fc6769_idx')],
            },
        ),
    ]
