# Generated by Django 5.2.6 on 2025-09-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gasto_user_mediopago_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediopago',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
