# Generated by Django 5.2.6 on 2025-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tokenactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('finanzas', 'Finanzas'), ('salud', 'Salud'), ('transporte', 'Transporte'), ('comida', 'Comida'), ('indumentaria', 'Indumentaria'), ('tecnologia', 'TecnologÃ\xada'), ('inversiones', 'Inversiones'), ('otros', 'Otros')], default='otros', max_length=24),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Peso Argentino'), ('USD', 'Dólar Americano'), ('RS', 'Real Brasileño'), ('CLP', 'Peso Chileno'), ('NA', 'Otros')], default='ARS', max_length=3),
        ),
    ]
