# Generated by Django 5.2.6 on 2025-09-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mediopago_tipo_tarjeta'),
        ('api', '0008_alter_gasto_categoria_alter_gasto_moneda'),
    ]

    operations = [
    ]
